
# cargo-vet audits file

[[audits.autocfg]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.5.0"

[[audits.bitflags]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "2.11.0"

[[audits.le-stream]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "8.0.0"

[[audits.le-stream-derive]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.3.2"

[[audits.macaddr]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.num-derive]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "0.4.2"

[[audits.num-traits]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "0.2.19"

[[audits.proc-macro2]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.106"

[[audits.quote]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.45"

[[audits.serde]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.228"

[[audits.serde_core]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.228"

[[audits.serde_derive]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.228"

[[audits.silizium]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "2.0.0"

[[audits.syn]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "2.0.117"

[[audits.unicode-ident]]
who = "Audited on 2026-03-26"
criteria = "safe-to-deploy"
version = "1.0.24"
