
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.le_stream]
url = "https://raw.githubusercontent.com/PaulmannLighting/le-stream/refs/heads/main/supply-chain/audits.toml"

[imports.le_stream_derive]
url = "https://raw.githubusercontent.com/PaulmannLighting/le-stream-derive/refs/heads/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.macaddr]]
version = "1.0.1"
criteria = "safe-to-deploy"
